name: Schedule Test

on:
  schedule:
    - cron: "*/5 * * * *"
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Scheduled test
        run: |
          echo "EVENT=${{ github.event_name }}"
          date -u
